In [141]:
import numpy as np 
import matplotlib.pyplot as plt
import scipy 
import scipy.linalg

###  1.1 Установить, какие произведения матриц  AB  и  BA  определены, и найти размерности полученных матриц:

а)  A  — матрица  4×2 ,  B  — матрица  4×2 ;

б)  A  — матрица  2×5 ,  B  — матрица  5×3 ;

в)  A  — матрица  8×3 ,  B  — матрица  3×8 ;

г)  A  — квадратная матрица  4×4 ,  B  — квадратная матрица  4×4 .

Проверим на примерах:

In [142]:
# а)
A1 = np.array([[1, -2], [4, -1], [1, 3], [1, -2]])
B1 = np.array([[4, 1], [5, -2], [2, 3], [2, -2]])

print(f'Матрица A\n{A1}\n')
print(f'Матрица B\n{B1}\n')

print(f'Матрица AB\n{np.dot(A1, B1)}')

Матрица A
[[ 1 -2]
 [ 4 -1]
 [ 1  3]
 [ 1 -2]]

Матрица B
[[ 4  1]
 [ 5 -2]
 [ 2  3]
 [ 2 -2]]



ValueError: shapes (4,2) and (4,2) not aligned: 2 (dim 1) != 4 (dim 0)

In [143]:
A1 = np.array([[1, -2], [4, -1], [1, 3], [1, -2]])
B1 = np.array([[4, 1], [5, -2], [2, 3], [2, -2]])

print(f'Матрица A\n{A1}\n')
print(f'Матрица B\n{B1}\n')

print(f'Матрица BA\n{np.dot(B1, A1)}')

Матрица A
[[ 1 -2]
 [ 4 -1]
 [ 1  3]
 [ 1 -2]]

Матрица B
[[ 4  1]
 [ 5 -2]
 [ 2  3]
 [ 2 -2]]



ValueError: shapes (4,2) and (4,2) not aligned: 2 (dim 1) != 4 (dim 0)

В обоих произведениях произведение не определено

In [144]:
# б)
A2 = np.array([[1, -2, 4, -1, 1], [1, 3, 1, -2, -1]])
B2 = np.array([[4, 1, 0], [5, -2, 1], [2, 3, -2], [2, -2, 3], [1, -1, -4]])

print(f'Матрица A\n{A2}\n')
print(f'Матрица B\n{B2}\n')

print(f'Матрица AB\n{np.dot(A2, B2)}')
print(f'Матрица BA\n{np.dot(B2, A2)}')

Матрица A
[[ 1 -2  4 -1  1]
 [ 1  3  1 -2 -1]]

Матрица B
[[ 4  1  0]
 [ 5 -2  1]
 [ 2  3 -2]
 [ 2 -2  3]
 [ 1 -1 -4]]

Матрица AB
[[  1  18 -17]
 [ 16   3  -1]]


ValueError: shapes (5,3) and (2,5) not aligned: 3 (dim 1) != 2 (dim 0)

Произведение матриц АВ определено (матрица размера 2х3), произведение ВА не определено

In [145]:
# в)
A3 = np.array([[1, -2, 4], [-1, 1, 0], [1, 3, 1], [-2, -1, 1], [1, -2, 4], [-1, 1, 0], [1, 3, 1], [-2, -1, 1]])
B3 = np.array([[4, 1, 0, 5, -2, 1, 2, 3], [-2, 2, -2, 3, 1, -1, -4, 0], [-2, 2, -2, 3, 1, -1, -4, 1]])

print(f'Матрица A\n{A3}\n')
print(f'Матрица B\n{B3}\n')

print(f'Матрица AB\n{np.dot(A3, B3)}')
print(f'Матрица BA\n{np.dot(B3, A3)}')

Матрица A
[[ 1 -2  4]
 [-1  1  0]
 [ 1  3  1]
 [-2 -1  1]
 [ 1 -2  4]
 [-1  1  0]
 [ 1  3  1]
 [-2 -1  1]]

Матрица B
[[ 4  1  0  5 -2  1  2  3]
 [-2  2 -2  3  1 -1 -4  0]
 [-2  2 -2  3  1 -1 -4  1]]

Матрица AB
[[  0   5  -4  11   0  -1  -6   7]
 [ -6   1  -2  -2   3  -2  -6  -3]
 [ -4   9  -8  17   2  -3 -14   4]
 [ -8  -2   0 -10   4  -2  -4  -5]
 [  0   5  -4  11   0  -1  -6   7]
 [ -6   1  -2  -2   3  -2  -6  -3]
 [ -4   9  -8  17   2  -3 -14   4]
 [ -8  -2   0 -10   4  -2  -4  -5]]
Матрица BA
[[-14  -4  18]
 [-14 -18  -7]
 [-16 -19  -6]]


Произведение матриц АВ определено (матрица размера 8х8), произведение ВА определено (матрица размера 3х3)

In [146]:
# г)
A4 = np.array([[1, -2, 4, 0], [-1, 1, 0, -2], [1, 3, 1, 0], [-2, -1, 1, 1]])
B4 = np.array([[4, 1, 0, 5], [-2, 2, -2, 3], [-2, 2, -2, 3], [-2, 1, -2, 3]])

print(f'Матрица A\n{A4}\n')
print(f'Матрица B\n{B4}\n')

print(f'Матрица AB\n{np.dot(A4, B4)}')
print(f'Матрица BA\n{np.dot(B4, A4)}')

Матрица A
[[ 1 -2  4  0]
 [-1  1  0 -2]
 [ 1  3  1  0]
 [-2 -1  1  1]]

Матрица B
[[ 4  1  0  5]
 [-2  2 -2  3]
 [-2  2 -2  3]
 [-2  1 -2  3]]

Матрица AB
[[  0   5  -4  11]
 [ -2  -1   2  -8]
 [ -4   9  -8  17]
 [-10  -1  -2  -7]]
Матрица BA
[[ -7 -12  21   3]
 [-12  -3  -7  -1]
 [-12  -3  -7  -1]
 [-11  -4  -7   1]]


Произведение матриц АВ  и ВА определено (матрица размера 4х4)

### 1.2. Найти сумму и произведение матриц

In [147]:
a = np.array([[1, -2], [3, 0]])
b = np.array([[4, -1], [0, 5]])

print(f'Матрица A\n{a}\n')
print(f'Матрица B\n{b}\n')
print(f'Матрица С = A + B\n{a + b}')
print(f'Матрица AB\n{np.dot(a, b)}')
print(f'Матрица BA\n{np.dot(b, a)}')

Матрица A
[[ 1 -2]
 [ 3  0]]

Матрица B
[[ 4 -1]
 [ 0  5]]

Матрица С = A + B
[[ 5 -3]
 [ 3  5]]
Матрица AB
[[  4 -11]
 [ 12  -3]]
Матрица BA
[[ 1 -8]
 [15  0]]


###  1.3. Из закономерностей сложения и умножения матриц на число можно сделать вывод, что матрицы одного размера образуют линейное пространство. Вычислить линейную комбинацию  3A−2B+4C

In [148]:
a1 = np.array([[1, 7], [3, -6]])
b1 = np.array([[0, 5], [2, -1]])
c1 = np.array([[2, -4], [1, 1]])

print(f'Матрица A\n{a1}\n')
print(f'Матрица B\n{b1}\n')
print(f'Матрица A\n{c1}\n')

print(f'Матрица D = 3A - 2B + 4C\n{3*a1 - 2*b1 + 4*c1}')

Матрица A
[[ 1  7]
 [ 3 -6]]

Матрица B
[[ 0  5]
 [ 2 -1]]

Матрица A
[[ 2 -4]
 [ 1  1]]

Матрица D = 3A - 2B + 4C
[[ 11  -5]
 [  9 -12]]


### 1.4 Вычислить 

In [149]:
A4 = np.array([[4, 1], [5, -2], [2, 3]])
print(f'Матрица:\n{A4}')
print(f'Транспонированная матрица:\n{A4.T}')
print(f'Матрица A*A_T:\n{np.dot(A4,(A4.T))}')
print(f'Матрица A_T*A:\n{np.dot((A4.T),A4)}')

Матрица:
[[ 4  1]
 [ 5 -2]
 [ 2  3]]
Транспонированная матрица:
[[ 4  5  2]
 [ 1 -2  3]]
Матрица A*A_T:
[[17 18 11]
 [18 29  4]
 [11  4 13]]
Матрица A_T*A:
[[45  0]
 [ 0 14]]


### 1. 5*. Написать на Python функцию для перемножения двух произвольных матриц, не используя NumPy.

In [150]:
a = np.array([[1, -2], [3, 0]])
b = np.array([[4, -1], [0, 5]])

# количество строк первой матрицы
m = len(a)                                            
# количество строк второй матрицы = количество столбцов первой матрицы
n = len(b)  
# количество столбцов второй матрицы
k = len(b[0])

# нулевая матрица размера mxk
c = [[0 for __ in range(k)] for __ in range(m)]  

result = c
for i in range(m):
    for j in range(k):       
        for k in range(n):
            result[i][j] += a[i][k] * b[k][j]

print(result)


[[4, -11], [12, 0]]


### 2.1.  Вычислить определитель:

In [151]:
# а)
A1 = np.array([[sin(x), -cos(x)], [cos(x), sin(x)]])

print(f'Матрица:\n{A1}')
print(f'Определитель:\n{np.linalg.det(A1)}')

Матрица:
[[sin(x) -cos(x)]
 [cos(x) sin(x)]]


TypeError: No loop matching the specified signature and casting was found for ufunc det

In [152]:
# б)
A1 = np.array([[4, 2, 3], [0, 5, 1], [0, 0, 9]])

print(f'Матрица:\n{A1}')
print(f'Определитель:\n{np.linalg.det(A1)}')

Матрица:
[[4 2 3]
 [0 5 1]
 [0 0 9]]
Определитель:
180.0


In [153]:
# в)
A1 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

print(f'Матрица:\n{A1}')
print(f'Определитель:\n{np.linalg.det(A1):.0f}')

Матрица:
[[1 2 3]
 [4 5 6]
 [7 8 9]]
Определитель:
0


### 2.3. Доказать, что матрица вырожденная

In [154]:
A2 = np.array([[-2, 7, -3], [4, -14, 6], [-3, 7, 13]])

print(f'Матрица:\n{A1}')
print(f'Определитель:\n{np.linalg.det(A2):.0f}')

Матрица:
[[1 2 3]
 [4 5 6]
 [7 8 9]]
Определитель:
0


Определитель равен 0, значит, матрица вырожденная.

###  2.4. Найти ранг матрицы:

In [155]:
# a)
A = np.array([[1, 2, 3], [1, 1, 1], [2, 3, 4]])

print(f'Матрица:\n{A}')
r = np.linalg.matrix_rank(A)
 
print(f'Ранг матрицы: {r}')

Матрица:
[[1 2 3]
 [1 1 1]
 [2 3 4]]
Ранг матрицы: 2


In [156]:
# б)
A = np.array([[0, 0, 2, 1], [0, 0, 2, 2], [0, 0, 4, 3], [2, 3, 5, 6]])

print(f'Матрица:\n{A}')
r = np.linalg.matrix_rank(A)
 
print(f'Ранг матрицы: {r}')

Матрица:
[[0 0 2 1]
 [0 0 2 2]
 [0 0 4 3]
 [2 3 5 6]]
Ранг матрицы: 3
